name = "ChaoticDynamicalSystemLibrary"
uuid = "55704126-756f-498a-a54f-434b72ecbddd"
authors = ["Nathanael Bosch <nathanael.bosch@uni-tuebingen.de> and contributors"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"

[compat]
ComponentArrays = "0.15"
JSON = "1"
LinearAlgebra = "1"
Markdown = "1"
SciMLBase = "1,2"
SimpleUnPack = "1"
Test = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
